### PR TITLE
[#234] fix null value handling in template processing

### LINKED ISSUE #234: Null Pointer Exception for JSON null values
Hi @pmaria,

I hope you are doing fine.

I ran into a `java.lang.NullPointerException` with carml `0.4.6` when using the JSON resolver.
I think it is because of a `null` value in JSON.

Mapping:  
[openalex_book_mapping.ttl.txt](https://github.com/carml/carml/files/10880491/openalex_book_mapping.ttl.txt)

JSON data: 
[W4280592420.json.txt](https://github.com/carml/carml/files/10880509/W4280592420.json.txt)

` java -jar carml-jar-1.0.0-SNAPSHOT-0.4.6.jar map  -m openalex_book_mapping.ttl -r . -of ttl` results in:

```
java.lang.NullPointerException
	at io.carml.engine.rdf.RdfTermGeneratorFactory.createNaturalRdfLexicalForm(RdfTermGeneratorFactory.java:483)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.carml.engine.GetTemplateValue.prepareValueForTemplate(GetTemplateValue.java:59)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.carml.engine.GetTemplateValue.lambda$bindTemplateExpression$1(GetTemplateValue.java:48)
	at io.carml.engine.template.CarmlTemplate$Builder.getExpressionValue(CarmlTemplate.java:101)
	at io.carml.engine.template.CarmlTemplate$Builder.getExpressionSegmentValue(CarmlTemplate.java:111)
	at io.carml.engine.template.CarmlTemplate$Builder.create(CarmlTemplate.java:171)
	at io.carml.engine.GetTemplateValue.apply(GetTemplateValue.java:42)
	at io.carml.engine.GetTemplateValue.apply(GetTemplateValue.java:15)
	at io.carml.engine.rdf.RdfTermGeneratorFactory.generateValues(RdfTermGeneratorFactory.java:195)
	at io.carml.engine.rdf.RdfTermGeneratorFactory.lambda$getGenerator$4(RdfTermGeneratorFactory.java:153)
	at io.carml.engine.rdf.RdfPredicateObjectMapper.lambda$map$9(RdfPredicateObjectMapper.java:185)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.carml.engine.rdf.RdfPredicateObjectMapper.map(RdfPredicateObjectMapper.java:187)
	at io.carml.engine.rdf.RdfTriplesMapper.lambda$mapEvaluation$8(RdfTriplesMapper.java:183)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:127)
	at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:70)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161)
	at io.carml.logicalsourceresolver.JsonPathResolver.lambda$bridgeAndListen$5(JsonPathResolver.java:142)
	at org.jsfr.json.DispatchUtil.dispatchValueToListeners(DispatchUtil.java:37)
	at org.jsfr.json.JsonCollector.endObject(JsonCollector.java:47)
	at org.jsfr.json.ContentDispatcher.endObject(ContentDispatcher.java:92)
	at org.jsfr.json.SurfingContext.endObject(SurfingContext.java:292)
	at org.jsfr.json.JacksonParser$JacksonResumableParser.doPare(JacksonParser.java:167)
	at org.jsfr.json.JacksonParser$JacksonResumableParser.parse(JacksonParser.java:145)
	at org.jsfr.json.JacksonParser$JacksonNonblockingParser.feed(JacksonParser.java:58)
	at io.carml.logicalsourceresolver.JsonPathResolver.readSource(JsonPathResolver.java:168)
	at io.carml.logicalsourceresolver.JsonPathResolver.lambda$getObjectFlux$3(JsonPathResolver.java:125)
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
	at reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:93)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8512)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8526)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2644)
	at io.carml.runner.output.Rdf4jOutputHandler.outputStreaming(Rdf4jOutputHandler.java:90)
	at io.carml.runner.CarmlMapCommand.outputRdf(CarmlMapCommand.java:200)
	at io.carml.runner.CarmlMapCommand.handleOutput(CarmlMapCommand.java:177)
	at io.carml.runner.CarmlMapCommand.call(CarmlMapCommand.java:106)
	at io.carml.runner.CarmlMapCommand.call(CarmlMapCommand.java:49)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at io.carml.runner.option.LoggingOptions.executionStrategy(LoggingOptions.java:43)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.carml.runner.CarmlRunner.run(CarmlRunner.java:33)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.carml.CarmlJarApplication.main(CarmlJarApplication.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2645)
		... 29 more

```

I figured that the problem is here in the mapping in `<#AuthorMapping>`:

```ttl
rr:predicateObjectMap [
    rr:predicate schema:affiliation ;
    rr:objectMap [
      rr:template "https://data.connectome.ch/openalex/organization/{institutions.*.id}" ;
      rr:termType rr:IRI
    ]
  ] .
```

because the `id` may be `null` in the data:

```json
"institutions": [
        {
          "id": null,
          "display_name": "Forest Research Institute, Department of Natural Forests, 6 Park Dyrekcyjny St., 17-230 Bia\u0142owie\u017ca, K.Pilch@ibles.waw.pl",
          "ror": null,
          "country_code": null,
          "type": null
        }
      ],
```

`id` is also referenced from the subject map in `<#OrganizationMapping>` but this does not throw an error which is fine. 

Expected behaviour: I would expect that no triple is created for a `null` value in both cases (predicate object map and subject map). 

In case you need more details, please let me know.

Thanks a lot and kind regards,

Tobias

### PR DESCRIPTION
**Pull request by pmaria**
fixes #234

### CODE REVIEW

File: carml-engine/src/main/java/io/carml/engine/GetTemplateValue.java [hunk 1]
```diff
@@ -45,22 +44,16 @@ public Optional<Object> apply(ExpressionEvaluation expressionEvaluation) {
   private void bindTemplateExpression(Expression expression, ExpressionEvaluation expressionEvaluation,
       Template.Builder templateBuilder) {
     templateBuilder.bind(expression, expr -> expressionEvaluation.apply(expr.getValue())
-        .map(this::prepareValueForTemplate));
+        .map(ExpressionEvaluation::extractValues)
```
Comment (tobiasschweizer) [inline carml-engine/src/main/java/io/carml/engine/GetTemplateValue.java:47]: `.map(ExpressionEvaluation::extractValues)` returns an `Optional<List<String>>` on which `.map(this::prepareExtractedValuesForTemplate));` is called. So now with `ExpressionEvaluation::extractValues` it is assured that the list does not contain `null` values, correct?

Was the problem that `this::prepareExtractedValuesForTemplate` was passed a `List` containing a `null` value? Then `createNaturalRdfLexicalForm` was called with `null`?

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueMultiValuedTemplate.rml.ttl [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
+
+<#TermTypeMappingLiteral> a rr:TriplesMap ;
+  rml:logicalSource [
+    rml:source "nullValues.json" ;
+    rml:referenceFormulation ql:JSONPath ;
+    rml:iterator "$" ;
+  ] ;
+  rr:subjectMap [
+    rr:template "http://example.com/Child/{$.Child[*].first}" ;
```
Comment (tobiasschweizer) [inline carml-engine/src/test/resources/RmlMapper/nullValues/nullValueMultiValuedTemplate.rml.ttl:14]: Is there a practical difference between the notations `[*].first` and `.*.first`?

File: carml-engine/src/test/java/io/carml/engine/iotests/RmlMapperTest.java [hunk 3]
```diff
@@ -194,6 +194,21 @@ void testSettingCustomBaseIri() {
...
+  @Test
+  void testMappingWithTemplateWithNullReference() {
+    testMapping("RmlMapper", "/RmlMapper/nullValues/nullValueTemplate.rml.ttl",
+        "/RmlMapper/nullValues/nullValueTemplate.output.ttl");
+  }
+
+  @Test
+  void testMappingWithTemplateWithMultiValuedNullReference() {
+    testMapping("RmlMapper", "/RmlMapper/nullValues/nullValueMultiValuedTemplate.rml.ttl",
+        "/RmlMapper/nullValues/nullValueMultiValuedTemplate.output.ttl");
```
Comment (tobiasschweizer) [inline carml-engine/src/test/java/io/carml/engine/iotests/RmlMapperTest.java:212]: `null` value in subject map, no triples are generated at all, correct?

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueTemplate.rml.ttl [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+<#TermTypeMappingLiteral> a rr:TriplesMap ;
+  rml:logicalSource [
+    rml:source "nullValues.json" ;
+    rml:referenceFormulation ql:JSONPath ;
+    rml:iterator "$.Child[*]" ;
+  ] ;
+
+  rr:subjectMap [
+    rr:template "http://example.com/Child/{first}{last}" ;
```
Comment (tobiasschweizer) [inline carml-engine/src/test/resources/RmlMapper/nullValues/nullValueTemplate.rml.ttl:15]: `first` is `null`, so no triples are generated, correct?

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+
+  rr:predicateObjectMap [
+    rr:predicateMap [
+      rr:constant ex:hasBirthday ;
+    ] ;
+    rr:objectMap [
+      rml:reference "birthday" ;
+      rr:datatype xsd:date ;
+      rr:termType rr:Literal ;
+    ] ;
```
Comment (tobiasschweizer) [inline carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl:27]: Would it make sense to add `first` in a predicate object map here? Since it is null, the expected result should be the same.

**Review by tobiasschweizer — COMMENTED** [review]
Looks good! I added a few comments to make sure that I understood the problem correctly and one suggestion for extending a test mapping.

File: carml-engine/src/main/java/io/carml/engine/GetTemplateValue.java (hunk 1 above)
Comment (pmaria) [reply carml-engine/src/main/java/io/carml/engine/GetTemplateValue.java:47]: correct

File: carml-engine/src/test/java/io/carml/engine/iotests/RmlMapperTest.java (hunk 3 above)
Comment (pmaria) [reply carml-engine/src/test/java/io/carml/engine/iotests/RmlMapperTest.java:212]: correct

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueTemplate.rml.ttl (hunk 4 above)
Comment (pmaria) [reply carml-engine/src/test/resources/RmlMapper/nullValues/nullValueTemplate.rml.ttl:15]: correct

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl (hunk 5 above)
Comment (pmaria) [reply carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl:27]: I don't think I follow

Comment (tobiasschweizer) [reply carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl:27]: like in the other test mapping `nullValueMultiValuedTemplate.rml.ttl`:

```ttl
 rr:predicateObjectMap [
    rr:predicate ex:knows ;
    rr:objectMap [
      rr:template "http://example.com/Child/{$.Child.*.first}" ;
    ] ;
  ] ;
```

Comment (tobiasschweizer) [reply carml-engine/src/test/resources/RmlMapper/nullValues/nullValueReference.rml.ttl:27]: Ok, great!

**Review by tobiasschweizer — APPROVED** [review]

File: carml-engine/src/test/resources/RmlMapper/nullValues/nullValueMultiValuedTemplate.rml.ttl (hunk 2 above)
Comment (pmaria) [reply carml-engine/src/test/resources/RmlMapper/nullValues/nullValueMultiValuedTemplate.rml.ttl:14]: No these are equivalent. There is some movement on standardization of JSONPath. See https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base and https://datatracker.ietf.org/doc/html/draft-ietf-jsonpath-base
